name: CI
on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build
      - uses: actions/upload-artifact@master
        with:
          name: linux-x64
          path: |
            ./dist/SuperScreenPi-*.AppImage
            ./dist/superscreenpi_*_amd64.deb
